{
    "name": "Taller Mecánico Plus",
    "version": "1.0",
    "depends": [
        "base",
        "fleet",
        "product",
        "mail",
        "base_automation",
    ],
    "author": "Tu Nombre",
    "category": "Services",
    "description": "Gestión de órdenes de trabajo de taller con integración VIN",
    "data": [
        # "data/email_templates.xml",
        # "data/automated_actions.xml",
        # "data/orden_trabajo_sequence.xml",
        "security/ir.model.access.csv",
        "report/report_action.xml",
        "report/orden_trabajo_report.xml",
        "views/fleet_vehicle_views.xml",
        "views/orden_trabajo_views.xml",
        "views/orden_trabajo_graph_views.xml",
        "views/orden_trabajo_filters.xml",
    ],
    "installable": True,
    "application": True,
}
